package com.mega.mvc06;


public class Problem06Main {

	public static void main(String[] args) {
		Problem05 error = new Problem05();
		try {
			error.call();
		} catch (Exception e) {
			System.out.println("호출한 곳에서 알아서 처리!");
		}
		System.out.println("에러 발생후 실행될까요?");
		System.out.println("에러 발생후 실행될까요?");
		System.out.println("에러 발생후 실행될까요?");
		System.out.println("에러 발생후 실행될까요?");
		System.out.println("에러 발생후 실행될까요?");
		System.out.println("에러 발생후 실행될까요?");
		System.out.println("에러 발생후 실행될까요?");
	}

}
